name: Libusb CI

on: [push]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev

    - name: Build
      run: |
        cmake -S . -B build
        cmake --build build --parallel 8

    - name: Build without udev (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cmake -S . -B build_no_udev -D WITH_UDEV=OFF
        cmake --build build_no_udev --parallel 8

